# -*- coding: utf-8 -*-
"""Rohith chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMoEu7pwDpJBEuFbuCMK13329XHhL5QA
"""

import random

def get_response(user_input):
    user_input = user_input.lower().strip()

    if user_input == "":
        return "I did not receive a message. Please type a question."

    if any(word in user_input for word in ["hello", "hi", "hey"]):
        return random.choice([
            "Hello! How can I help you today?",
            "Hi! Welcome to the Student Help Chatbot.",
            "Hello! Type 'help' to see what I can do."
        ])

    elif "help" in user_input or "what can you do" in user_input:
        return (
            "I can help with:\n"
            "1. School hours\n"
            "2. Course information\n"
            "3. Registration\n"
            "4. Contact information\n"
            "5. Financial aid"
        )

    elif "hours" in user_input or "open" in user_input:
        return "Student services are available Monday through Friday from 8:00 AM to 5:00 PM."

    elif "course" in user_input or "class" in user_input:
        return "The university offers courses in business, IT, project management, cybersecurity, and other areas."

    elif "register" in user_input or "registration" in user_input:
        return "Log in to your student portal and select the registration option."

    elif "contact" in user_input or "support" in user_input:
        return "You can contact student support through the university website or student portal."

    elif "financial aid" in user_input or "scholarship" in user_input:
        return "Please contact the financial aid office for scholarship and financial aid information."

    elif "thank" in user_input:
        return "You're welcome!"

    elif "bye" in user_input or "goodbye" in user_input or "exit" in user_input:
        return "Goodbye! Have a great day."

    else:
        return "I'm sorry, I did not understand that question. Type 'help' to see what I can answer."


print("ROHITH STUDENT HELP CHATBOT")
print("Type 'help' to see my capabilities.")
print("Type 'exit' to end the conversation.")

while True:
    user_message = input("\nYou: ")
    response = get_response(user_message)
    print("Bot:", response)

    if user_message.lower().strip() in ["exit", "bye", "goodbye"]:
        break